// Wired-table census.
//
// Operationalizes the methodology from docs/adr/0001-repo-consolidation-strategy.md:
// classify every Drizzle table in shared/schema.ts as WIRED (referenced by
// server code) or ROADMAP/unwired (defined but never referenced outside the
// schema). "Referenced by server code" = the table's exported variable name
// appears in at least one non-test file under server/ (excluding *.test.ts and
// shared/schema.ts itself).
//
// Usage:
//   npx tsx scripts/wired-tables-report.ts            # print summary
//   npx tsx scripts/wired-tables-report.ts --markdown # write docs/SCHEMA-STATUS.md
//   npx tsx scripts/wired-tables-report.ts --json      # print machine-readable JSON
//
// This is a documentation/audit tool, not a CI gate. Re-run it after wiring or
// removing tables to keep docs/SCHEMA-STATUS.md honest.

import fs from "node:fs";
import path from "node:path";

// Tolerate a closed pipe (e.g. `... | head`) without a noisy EPIPE crash.
process.stdout.on("error", (err: NodeJS.ErrnoException) => {
  if (err.code === "EPIPE") process.exit(0);
  throw err;
});

const ROOT = process.cwd();
const SCHEMA = path.join(ROOT, "shared", "schema.ts");
const SERVER_DIR = path.join(ROOT, "server");

interface TableInfo {
  varName: string;
  tableName: string;
  wired: boolean;
  refFiles: string[];
}

function listServerFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...listServerFiles(p));
    } else if (entry.name.endsWith(".ts") && !entry.name.endsWith(".test.ts")) {
      out.push(p);
    }
  }
  return out;
}

function parseTables(schemaSrc: string): { varName: string; tableName: string }[] {
  const tables: { varName: string; tableName: string }[] = [];
  // Match `export const <var> = pgTable(` then the first quoted string after it
  // (the table name may sit on the same or the next line).
  const re = /export const (\w+) = pgTable\(\s*["']([^"']+)["']/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(schemaSrc)) !== null) {
    tables.push({ varName: m[1], tableName: m[2] });
  }
  return tables;
}

function main(): void {
  const schemaSrc = fs.readFileSync(SCHEMA, "utf8");
  const tables = parseTables(schemaSrc);
  const serverFiles = listServerFiles(SERVER_DIR).filter(
    (f) => path.resolve(f) !== path.resolve(SCHEMA),
  );
  const fileContents = serverFiles.map((f) => ({ file: f, src: fs.readFileSync(f, "utf8") }));

  const infos: TableInfo[] = tables.map(({ varName, tableName }) => {
    const word = new RegExp(`\\b${varName}\\b`);
    const refFiles = fileContents
      .filter(({ src }) => word.test(src))
      .map(({ file }) => path.relative(ROOT, file));
    return { varName, tableName, wired: refFiles.length > 0, refFiles };
  });

  const wired = infos.filter((t) => t.wired);
  const roadmap = infos.filter((t) => !t.wired);

  if (process.argv.includes("--json")) {
    process.stdout.write(
      JSON.stringify(
        {
          total: infos.length,
          wired: wired.length,
          roadmap: roadmap.length,
          roadmapVars: roadmap.map((t) => t.varName),
        },
        null,
        2,
      ) + "\n",
    );
    return;
  }

  if (process.argv.includes("--markdown")) {
    const md = renderMarkdown(infos);
    fs.writeFileSync(path.join(ROOT, "docs", "SCHEMA-STATUS.md"), md);
    process.stdout.write(`Wrote docs/SCHEMA-STATUS.md — ${wired.length} wired, ${roadmap.length} roadmap.\n`);
    return;
  }

  process.stdout.write(
    `Tables: ${infos.length}  |  wired: ${wired.length}  |  roadmap (unwired): ${roadmap.length}\n\n`,
  );
  process.stdout.write("Roadmap (unwired) tables:\n");
  for (const t of roadmap) process.stdout.write(`  - ${t.varName} (${t.tableName})\n`);
}

function renderMarkdown(infos: TableInfo[]): string {
  const wired = infos.filter((t) => t.wired);
  const roadmap = infos.filter((t) => !t.wired);
  const lines: string[] = [];
  lines.push("# Schema status — wired vs roadmap");
  lines.push("");
  lines.push(
    "Generated by `npx tsx scripts/wired-tables-report.ts --markdown`. Do not edit by hand — re-run the script.",
  );
  lines.push("");
  lines.push(
    "A table is **wired** when its exported variable is referenced by at least one " +
      "non-test file under `server/` (excluding `shared/schema.ts`). **Roadmap** tables " +
      "are defined in the schema but have no server references yet — they are created by " +
      "`db:push`/migrations but no code reads or writes them. See ADR 0001 for why this matters.",
  );
  lines.push("");
  lines.push(`- **Total tables:** ${infos.length}`);
  lines.push(`- **Wired:** ${wired.length}`);
  lines.push(`- **Roadmap (unwired):** ${roadmap.length}`);
  lines.push("");
  lines.push("## Roadmap (unwired) tables");
  lines.push("");
  lines.push("| Table | Variable |");
  lines.push("|---|---|");
  for (const t of roadmap) lines.push(`| \`${t.tableName}\` | \`${t.varName}\` |`);
  lines.push("");
  lines.push("## Wired tables");
  lines.push("");
  lines.push("| Table | Variable | Referenced in (sample) |");
  lines.push("|---|---|---|");
  for (const t of wired) {
    const sample = t.refFiles.slice(0, 3).join(", ") + (t.refFiles.length > 3 ? ", …" : "");
    lines.push(`| \`${t.tableName}\` | \`${t.varName}\` | ${sample} |`);
  }
  lines.push("");
  return lines.join("\n");
}

main();
